# Generated by Django 4.2.7 on 2024-02-29 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BookTabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabelno', models.IntegerField()),
                ('noofperson', models.IntegerField()),
                ('intime', models.TimeField()),
                ('outtime', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('tabelno', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TabelInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurent.booktabel')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Restname', models.CharField(max_length=50)),
                ('totaltabel', models.IntegerField(default=10)),
                ('Admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurent.adminuser')),
            ],
        ),
        migrations.AddField(
            model_name='booktabel',
            name='restaurent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurent.restaurent'),
        ),
    ]
