# Generated by Django 4.2.7 on 2024-02-29 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabelinfo',
            name='persons',
            field=models.ManyToManyField(to='Restaurent.person'),
        ),
    ]
