# Generated by Django 4.2.7 on 2024-02-29 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurent', '0002_tabelinfo_persons'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='restaurent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Restaurent.restaurent'),
        ),
    ]
