# Generated by Django 4.2.7 on 2024-02-29 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurent', '0005_rename_persons_bookings_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='person',
            new_name='persons',
        ),
    ]
