# Generated by Django 4.2.7 on 2024-03-05 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Restaurent', '0007_bookings_tabelno_persons_tabelno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurent',
            name='Admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
