# Generated by Django 4.2.7 on 2024-03-06 05:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurent', '0013_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurent',
            name='rating',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
