# Generated by Django 4.2.7 on 2024-03-06 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurent', '0015_moneywallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='restname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Restaurent.restaurent'),
        ),
    ]
