# Generated by Django 4.2.7 on 2024-03-06 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurent', '0016_bookings_restname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='restname',
        ),
    ]
