# Generated by Django 4.2.7 on 2024-03-06 11:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Restaurent', '0017_remove_bookings_restname'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noofpersons', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('persons', models.ManyToManyField(to='Restaurent.persons')),
                ('restname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurent.restaurent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
