# Generated by Django 4.2.7 on 2024-03-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurent', '0018_bookingtable'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingtable',
            name='tabelno',
            field=models.IntegerField(default=1),
        ),
    ]
