# Generated by Django 4.2.7 on 2024-03-06 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurent', '0019_bookingtable_tabelno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persons',
            name='tabelno',
        ),
    ]
