# Generated by Django 4.2.7 on 2024-03-07 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurent', '0022_onlinefoodorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OnlineFoodOrder',
        ),
    ]
