# Generated by Django 4.2.7 on 2024-03-07 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Restaurent', '0023_delete_onlinefoodorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineFoodOrder',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=10)),
                ('created_at', models.DateField(auto_now=True)),
                ('foods', models.ManyToManyField(to='Restaurent.food')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
