# Generated by Django 4.2.7 on 2024-03-07 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurent', '0024_onlinefoodorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlinefoodorder',
            name='foods',
        ),
        migrations.RemoveField(
            model_name='onlinefoodorder',
            name='user',
        ),
        migrations.DeleteModel(
            name='ExampleRestaurant',
        ),
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.DeleteModel(
            name='OnlineFoodOrder',
        ),
    ]
