# Generated by Django 4.2.7 on 2024-03-07 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurent', '0025_remove_onlinefoodorder_foods_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodname', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('type', models.CharField(choices=[('VEG', 'Vegetarian'), ('NON_VEG', 'Non-Vegetarian')], max_length=10)),
                ('image', models.ImageField(upload_to='food/food-img')),
                ('restname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurent.restaurent')),
            ],
        ),
    ]
